### ISSUE TITLE
Integration stops after some time, needs to be restarted

### ISSUE THREAD

**Issue by kgeusens** [Sholofly/arrisdcx960#24]
**Describe the bug**
DCX960 integration stops working after some time of inactivity, stack trace in log.
Connected to Telenet.
Log trace contains:
File "/usr/local/lib/python3.9/site-packages/arris_dcx960/arrisdcx960.py", line 300, in _on_mqtt_client_connect

**To Reproduce**
Integration works fine when interactive. I notice the problem the next day when the mediaplayer seems unresponsive.
Checking HA, the integration is no longer active and needs to be restarted.

**Expected behavior**
For this wonderful integration to stay online :)

**Screenshots**
N/A

**Version of the component**
1.2.0

**Logging**
Traceback (most recent call last):
File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.9/threading.py", line 910, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
self.loop_forever(retry_first_connection=True)
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
rc = self._loop(timeout)
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
rc = self.loop_read()
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
rc = self._packet_read()
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
rc = self._packet_handle()
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3039, in _packet_handle
return self._handle_connack()
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3138, in _handle_connack
on_connect(
File "/usr/local/lib/python3.9/site-packages/arris_dcx960/arrisdcx960.py", line 300, in _on_mqtt_client_connect
client.connect(self._mqtt_broker, DEFAULT_PORT)
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 914, in connect
return self.reconnect()
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1080, in reconnect
sock = WebsocketWrapper(sock, self._host, self._port, self._ssl,
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3713, in __init__
self._do_handshake(extra_headers)
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3756, in _do_handshake
byte = self._socket.recv(1)
File "/usr/local/lib/python3.9/ssl.py", line 1226, in recv
return self.read(buflen)
File "/usr/local/lib/python3.9/ssl.py", line 1101, in read
return self._sslobj.read(len)
ConnectionResetError: [Errno 104] Connection reset by peer

**Additional context**
N/A

**Comment by RobDiederen** [comment]
I have a similar problem, I think it happes with my integration because I turn off the power on the media box (ziggo Media box) at night and if I leave my house.
Is it possible to reload the integration after the media box has restarted or something ?

**Comment by Fifke** [comment]
Same problem here. Even if the box is switched on for several hours it became not responding... Very anoying because i use Alexa to switch it off true home assistant. When i restart the integration it works again... Telenet box.

**Comment by StevenBrs** [comment]
Hi there
First of all, thanks for this great integration!
I also have above issue with a Telenet TV box. After a while the integration has to be restarted and after that works perfectly again (for a while).

versions:
- HA: 2022.8.7
- HACS: 1.27.1
- Arris DCX960: 1.2.0

**Comment by Sholofly** [comment]
Hi there. This component is not functional anymore. I'm continuing here: https://github.com/Sholofly/lghorizon
For now only Ziggo but I'm trying to connect other providers in the future. I hope i can fix this issue there
