### ISSUE TITLE
Ziggo modified API

### ISSUE THREAD

**Issue by bkbartk** [Sholofly/arrisdcx960#26]
I'm not sure what happened. but it looks like ziggo has limited the maximum amount of request or concurrent logins.

When I restarted HA the addon would't come up and I had the error below. I also count's login to any ziggo service so I changed my pw.
then I could login, and I reinstalled the add on. after that the addon would install using the credentials. but would start because of incorrect credentials.
Also I couldn't login to any ziggo services anymore untill I disabled the add on. When enabling the addon would start but I can't login to any ziggo services anymore.

So I think ziggo has changed something in there api not allowing this many logins or requests.

> 2022-02-21 16:23:45 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-21 16:23:45 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration arris_dcx960 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-21 16:23:45 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration browser_mod which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-21 16:23:52 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1894964600] Received invalid command: browser_mod/connect
2022-02-21 16:23:52 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1894964600] Received invalid command: energy/info
2022-02-21 16:23:59 DEBUG (SyncWorker_3) [arris_dcx960.arrisdcx960] [{'type': 'state', 'code': 'invalidCredentials', 'reason': 'invalid'}]
2022-02-21 16:24:01 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry <username> for arris_dcx960
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/arris_dcx960/__init__.py", line 45, in async_setup_entry
    await hass.async_add_executor_job(api.connect)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/arris_dcx960/arrisdcx960.py", line 356, in connect
    self.get_session_and_token()
  File "/usr/local/lib/python3.9/site-packages/arris_dcx960/arrisdcx960.py", line 68, in get_session_and_token
    self.get_session()
  File "/usr/local/lib/python3.9/site-packages/arris_dcx960/arrisdcx960.py", line 76, in get_session
    self.get_default_session()
  File "/usr/local/lib/python3.9/site-packages/arris_dcx960/arrisdcx960.py", line 90, in get_default_session
    raise ArrisDCX960AuthenticationError("Invalid credentials")
arris_dcx960.exceptions.ArrisDCX960AuthenticationError: Invalid credentials
2022-02-21 16:24:10 WARNING (MainThread) [homeassistant.config_entries] Config entry 'HP ENVY 5000 series [E25F21]' for ipp integration not ready yet: Invalid response from API: Timeout occurred while connecting to IPP server.; Retrying in background
2022-02-21 16:24:53 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for doorbell @ 192.168.178.209: Timeout while connecting to ('192.168.178.209', 6053)

**Comment by Sholofly** [comment]
Strange, I have three Ziggo boxes ATM and even when they're all active and I'm connected on the ZiggoGo website, I'm still able to use the component. Are you still facing this issue?

**Comment by bkbartk** [comment]
no, not anymore,
I had this issue for a day or 2 and I expected something to be changed, but probably this was a bug and not a feature.

**Comment by Sholofly** [comment]
In issue #27 I will keep track of my progress in making the component continue after such outages. Thanks for the feedback!
