### ISSUE TITLE
Integration can't login

### ISSUE THREAD

**Issue by JBakers** [Sholofly/arrisdcx960#27]
Ziggo integration can't login anymore.

Sadly i tried removing the integration and reinstall it to try and fix it.
`2022-03-10 21:51:46 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Ziggo Next for arris_dcx960
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/config_entries.py", line 313, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/home/homeassistant/.homeassistant/custom_components/arris_dcx960/__init__.py", line 45, in async_setup_entry
await hass.async_add_executor_job(api.connect)
File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/srv/homeassistant/lib/python3.9/site-packages/arris_dcx960/arrisdcx960.py", line 361, in connect
self.mqtt_client.connect(self._mqtt_broker, DEFAULT_PORT)
File "/srv/homeassistant/lib/python3.9/site-packages/paho/mqtt/client.py", line 914, in connect
return self.reconnect()
File "/srv/homeassistant/lib/python3.9/site-packages/paho/mqtt/client.py", line 1080, in reconnect
sock = WebsocketWrapper(sock, self._host, self._port, self._ssl,
File "/srv/homeassistant/lib/python3.9/site-packages/paho/mqtt/client.py", line 3713, in __init__
self._do_handshake(extra_headers)
File "/srv/homeassistant/lib/python3.9/site-packages/paho/mqtt/client.py", line 3756, in _do_handshake
byte = self._socket.recv(1)
File "/usr/lib/python3.9/ssl.py", line 1226, in recv
return self.read(buflen)
File "/usr/lib/python3.9/ssl.py", line 1101, in read
return self._sslobj.read(len)
ConnectionResetError: [Errno 104] Connection reset by peer`

**Comment by guidostek** [comment]
Same here. Integration stopped working two nights ago. I noticed because my automations for lights based on the mediabox stopped working.

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/arris_dcx960/__init__.py", line 45, in async_setup_entry
    await hass.async_add_executor_job(api.connect)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/arris_dcx960/arrisdcx960.py", line 361, in connect
    self.mqtt_client.connect(self._mqtt_broker, DEFAULT_PORT)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1080, in reconnect
    sock = WebsocketWrapper(sock, self._host, self._port, self._ssl,
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3713, in __init__
    self._do_handshake(extra_headers)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3756, in _do_handshake
    byte = self._socket.recv(1)
  File "/usr/local/lib/python3.9/ssl.py", line 1226, in recv
    return self.read(buflen)
  File "/usr/local/lib/python3.9/ssl.py", line 1101, in read
    return self._sslobj.read(len)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by Sholofly** [comment]
Thanks for reaching out. I can't reproduce the error in any way. Analyzing your log files it looks like the connection with the mqtt server did not succeed, due to an error on the Ziggo side. Of course this should be handled by the component, but can't figure out how to do that in a good way. I dive in further as soon as I have time.

**Comment by guidostek** [comment]
I had several web services quitting on me during the last couple of days.  Several reboots and now I am connected again.

No idear why it did not work two days in a row.

**Comment by JBakers** [comment]
I still cant connect.
I removed the integration, but cant reinstall it because also the initial setup (username/pass/provider) says it can't connect.

**Comment by Dyka007** [comment]
i have the same problem as @JBakers it is only not ziggo but telenet, can anyone help me?

**Comment by Sholofly** [comment]
Hi there. This component is not functional anymore. I'm continuing here: https://github.com/Sholofly/lghorizon
For now only Ziggo but I'm trying to connect other providers in the future
