### ISSUE TITLE
Updating arris_dcx960 sensor took longer than the scheduled update interval 0:00:30

### ISSUE THREAD

**Issue by golles** [Sholofly/arrisdcx960#34]
**Describe the bug**
Since a couple of days, I get hundreds of these log lines

**To Reproduce**
n/a

**Expected behavior**
Obviously, the component to be able to update the state of the mediabox :-)

**Screenshots**
n/a

**Version of the component**
1.2.0
arris-dcx960==0.2.1

**Logging**
```yaml
2022-06-25 21:31:49 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139650618500720] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 107, in async_handle
    handler(self.hass, self, schema(msg))
  File "/usr/src/homeassistant/homeassistant/components/search/__init__.py", line 54, in websocket_search_related
    msg["id"], searcher.async_search(msg["item_type"], msg["item_id"])
  File "/usr/src/homeassistant/homeassistant/components/search/__init__.py", line 96, in async_search
    getattr(self, f"_resolve_{search_type}")(search_id)
  File "/usr/src/homeassistant/homeassistant/components/search/__init__.py", line 183, in _resolve_entity
    for entity in script.scripts_with_entity(self.hass, entity_id):
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 89, in scripts_with_entity
    return [
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 92, in <listcomp>
    if entity_id in script_entity.script.referenced_entities
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1370, in referenced_entities
    Script._find_referenced_entities(self._referenced_entities, self.sequence)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1385, in _find_referenced_entities
    _referenced_extract_ids(data, ATTR_ENTITY_ID, referenced)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1117, in _referenced_extract_ids
    item_ids = data.get(key)
AttributeError: 'Template' object has no attribute 'get'
2022-06-25 21:32:17 DEBUG (SyncWorker_7) [arris_dcx960.arrisdcx960] Doing API call with url: https://web-api-prod-obo.horizon.tv/oesp/v4/NL/nld/web/networkdvrrecordings/quota
2022-06-25 21:32:17 DEBUG (SyncWorker_7) [arris_dcx960.arrisdcx960] Raw result: {"quota":1440000,"occupied":376440}
2022-06-25 21:32:32 DEBUG (Thread-106) [arris_dcx960.arrisdcx960] mqtt message received on topic "16930449_nl": {'version': '1.4.1', 'type': 'CPE.uiStatus', 'source': '3C36E4-EOSSTB-003926772108', 'messageTimeStamp': 1656185552522, 'status': {'uiStatus': 'mainUI', 'playerState': {'sourceType': 'linear', 'speed': 1, 'lastSpeedChangeTime': 1656184493218, 'source': {'channelId': 'NL_000007_019181', 'eventId': 'crid:~~2F~~2Fgn.tv~~2F13242706~~2FMV009279540000,imi:6da7ac1eb9b8f2b1b894024761b7d7216b8133a9'}}, 'uiState': {}}}
2022-06-25 21:32:32 DEBUG (Thread-106) [arris_dcx960.arrisdcx960box] Updating box 3C36E4-EOSSTB-003926772108 with payload
2022-06-25 21:32:32 DEBUG (Thread-106) [arris_dcx960.arrisdcx960box] Callback called from box 3C36E4-EOSSTB-003926772108
2022-06-25 21:32:33 DEBUG (Thread-106) [arris_dcx960.arrisdcx960] mqtt message received on topic "16930449_nl/3C36E4-EOSSTB-003926772108/status": {'deviceType': 'STB', 'source': '3C36E4-EOSSTB-003926772108', 'state': 'ONLINE_STANDBY', 'mac': '9C:C8:FC:2F:49:20', 'ipAddress': '192.168.68.115/255.255.255.0'}
2022-06-25 21:32:33 DEBUG (Thread-106) [arris_dcx960.arrisdcx960box] Callback called from box 3C36E4-EOSSTB-003926772108
2022-06-25 21:32:47 DEBUG (SyncWorker_11) [arris_dcx960.arrisdcx960] Doing API call with url: https://web-api-prod-obo.horizon.tv/oesp/v4/NL/nld/web/networkdvrrecordings/quota
2022-06-25 21:32:47 DEBUG (SyncWorker_11) [arris_dcx960.arrisdcx960] Raw result: {"quota":1440000,"occupied":376440}
2022-06-25 21:33:17 DEBUG (SyncWorker_0) [arris_dcx960.arrisdcx960] Doing API call with url: https://web-api-prod-obo.horizon.tv/oesp/v4/NL/nld/web/networkdvrrecordings/quota
2022-06-25 21:33:17 DEBUG (SyncWorker_0) [arris_dcx960.arrisdcx960] Raw result: {"quota":1440000,"occupied":376440}
2022-06-25 21:33:47 DEBUG (SyncWorker_11) [arris_dcx960.arrisdcx960] Doing API call with url: https://web-api-prod-obo.horizon.tv/oesp/v4/NL/nld/web/networkdvrrecordings/quota
2022-06-25 21:33:47 DEBUG (SyncWorker_11) [arris_dcx960.arrisdcx960] Raw result: {"quota":1440000,"occupied":376440}
2022-06-25 21:34:17 DEBUG (SyncWorker_9) [arris_dcx960.arrisdcx960] Doing API call with url: https://web-api-prod-obo.horizon.tv/oesp/v4/NL/nld/web/networkdvrrecordings/quota
2022-06-25 21:34:17 DEBUG (SyncWorker_9) [arris_dcx960.arrisdcx960] Raw result: {"quota":1440000,"occupied":376440}
2022-06-25 21:34:47 DEBUG (SyncWorker_4) [arris_dcx960.arrisdcx960] Doing API call with url: https://web-api-prod-obo.horizon.tv/oesp/v4/NL/nld/web/networkdvrrecordings/quota
2022-06-25 21:34:47 DEBUG (SyncWorker_4) [arris_dcx960.arrisdcx960] Raw result: {"quota":1440000,"occupied":376440}
2022-06-25 21:35:17 DEBUG (SyncWorker_6) [arris_dcx960.arrisdcx960] Doing API call with url: https://web-api-prod-obo.horizon.tv/oesp/v4/NL/nld/web/networkdvrrecordings/quota
2022-06-25 21:35:27 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.bla_recording_capacity is taking over 10 seconds
2022-06-25 21:35:47 WARNING (MainThread) [homeassistant.components.sensor] Updating arris_dcx960 sensor took longer than the scheduled update interval 0:00:30
2022-06-25 21:36:17 WARNING (MainThread) [homeassistant.components.sensor] Updating arris_dcx960 sensor took longer than the scheduled update interval 0:00:30
2022-06-25 21:36:47 WARNING (MainThread) [homeassistant.components.sensor] Updating arris_dcx960 sensor took longer than the scheduled update interval 0:00:30
2022-06-25 21:37:17 WARNING (MainThread) [homeassistant.components.sensor] Updating arris_dcx960 sensor took longer than the scheduled update interval 0:00:30
2022-06-25 21:37:47 WARNING (MainThread) [homeassistant.components.sensor] Updating arris_dcx960 sensor took longer than the scheduled update interval 0:00:30
2022-06-25 21:38:17 WARNING (MainThread) [homeassistant.components.sensor] Updating arris_dcx960 sensor took longer than the scheduled update interval 0:00:30
...
```

**Additional context**
Not sure if the`homeassistant.components.websocket_api.http.connection` error is caused by this component or something else.
It also looks like there are parallel quota calls happening at the same time

In 9 hours I got almost 1600 of these error lines in my logs.

**Comment by golles** [comment]
I think this was likely due to an issue on the provider's side, haven't seen this in the last 3 days.

**Comment by golles** [comment]
Hmm, one day after closing, it's back

**Comment by twoenter** [comment]
Yes I have the same issue. But it is working here for like a day and than the states of ziggo media box and media box mini go to unavailable...

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:778
Integration: Sensor (documentation, issues)
First occurred: 6 september 2022 om 17:05:36 (13 occurrences)
Last logged: 7 september 2022 om 21:34:41

Updating arris_dcx960 sensor took longer than the scheduled update interval 0:00:30
```

The media boxes are still online though. After reloading the integration everything works well.

**Comment by Sholofly** [comment]
Hi there. This component is not functional anymore. I'm continuing here: https://github.com/Sholofly/lghorizon
For now only Ziggo but I'm trying to connect other providers in the future
