### ISSUE TITLE
Cannot connect to mediabox anymore. Cannot reinstall the integration either

### ISSUE THREAD

**Issue by marcokreeft87** [Sholofly/arrisdcx960#41]
**Describe the bug**
Can't connect to my Ziggo Mediabox Next anymore. Gives a cannot_connect error

**To Reproduce**

1. Download the integration
2. Login

**Expected behavior**
The integration is configured and I can control the mediabox

**Screenshots**

**Version of the component**
1.2.0

**Logging**
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/arris_dcx960/__init__.py", line 45, in async_setup_entry
    await hass.async_add_executor_job(api.connect)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/arris_dcx960/arrisdcx960.py", line 356, in connect
    self.get_session_and_token()
  File "/usr/local/lib/python3.10/site-packages/arris_dcx960/arrisdcx960.py", line 69, in get_session_and_token
    self._get_token()
  File "/usr/local/lib/python3.10/site-packages/arris_dcx960/arrisdcx960.py", line 350, in _get_token
    jsonResult = self._do_api_call(self._api_url_token)
  File "/usr/local/lib/python3.10/site-packages/arris_dcx960/arrisdcx960.py", line 344, in _do_api_call
    raise ArrisDCX960ConnectionError(
arris_dcx960.exceptions.ArrisDCX960ConnectionError: API call failed: 404
```

**Comment by PierreLevres** [comment]
Known issue, see https://github.com/Sholofly/arrisdcx960/issues/39 with comment: closed, new custom component on its way...

**Comment by Sholofly** [comment]
What @PierreLevres says Marco. Since you're using Ziggo I would like to use your experiences. Please move over to https://github.com/Sholofly/lghorizon and report your findings. Thanks for using the component!
