### ISSUE TITLE
Error while initializing Home Assistant component

### ISSUE THREAD

**Issue by dennisvdheuvel** [Sholofly/arrisdcx960#43]
The component can't be initialized anymore. I tried to re-install and reconfig the component, but then I get the error 'Cant connect'. I try to add a 'Ziggo' account. Below the debug info;

Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant.config_entries
Source: custom_components/arris_dcx960/__init__.py:45
Integration: Arris DCX960 (documentation, issues)
First occurred: 14:01:04 (1 occurrences)
Last logged: 14:01:04

Error setting up entry dennis@fineapp.nl for arris_dcx960
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/arris_dcx960/__init__.py", line 45, in async_setup_entry
    await hass.async_add_executor_job(api.connect)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/arris_dcx960/arrisdcx960.py", line 356, in connect
    self.get_session_and_token()
  File "/usr/local/lib/python3.10/site-packages/arris_dcx960/arrisdcx960.py", line 69, in get_session_and_token
    self._get_token()
  File "/usr/local/lib/python3.10/site-packages/arris_dcx960/arrisdcx960.py", line 350, in _get_token
    jsonResult = self._do_api_call(self._api_url_token)
  File "/usr/local/lib/python3.10/site-packages/arris_dcx960/arrisdcx960.py", line 344, in _do_api_call
    raise ArrisDCX960ConnectionError(
arris_dcx960.exceptions.ArrisDCX960ConnectionError: API call failed: 404

**Comment by Sholofly** [comment]
@dennisvdheuvel Hi Dennis, move over to https://github.com/Sholofly/lghorizon-python
